# version: '3.8'

services:
  laravel_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: always
    volumes:
      - .:/var/www
      - ./database/database.sqlite:/var/www/database/database.sqlite
    networks:
      - laravel_network
    depends_on:
      - nginx

  nginx:
    image: nginx:latest
    container_name: laravel_nginx
    restart: always
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel_network

volumes:
  sqlite_data:

networks:
  laravel_network:
    driver: bridge
